language: python
python: 2.7
env:
  - TOX_ENV=pep8
  - TOX_ENV=isort
#  - TOXENV=py27
#  - TOXENV=py33
#  - TOXENV=py34
#  - TOXENV=py35

before_install:
  - time pip install tox

script:
  - tox -e $TOX_ENV

notifications:
  email:
    on_success: never
    on_failure: never
